#!/bin/sh -e

BUILD_TYPE=${BUILD_TYPE:-RelWithDebInfo}
RELOADABLE=${RELOADABLE:-ON}

if [ "${RELOADABLE}" = "ON" ]
then
	SUFFIX="reloadable"
else
	SUFFIX="static"
fi

BUILD_DIR="${BUILD_TYPE}-${SUFFIX}"

exec ~/.steam/steam/steamapps/common/SteamLinuxRuntime_4/run --share-pid -- \
    bin/steamrt/${BUILD_DIR}/grain-editor
